version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10.0

    working_directory: ~/repo

    steps:
    - checkout

    - restore_cache:
        name: Restore node_modules
        key: npm-cache-{{ checksum "package.json" }}

    ## Install and cache dependencies
    - run: meteor || curl https://install.meteor.com/ | /bin/sh
    - run: meteor npm install

    - save_cache:
        name: Save node_modules
        key: npm-cache-{{ checksum "package.json" }}
        paths:
        - '~/.npm'
        - 'node_modules'

    - run: echo $METEOR_SETTINGS > settings.json
    - run: echo $METEOR_SESSION > meteor_session.json
    - run: export METEOR_SESSION_FILE=/home/repo/meteor_session.json
    - run: npm run build
    - run: npm test -- --once

    - deploy:
        command: |
          rm -rf node_modules
          METEOR_SESSION_FILE=meteor_session.json meteor publish
        filters:
          tags:
            only: /^v.*/